### ISSUE TITLE
Denying assistance opportunities

### ISSUE THREAD

**Issue by lannesnunes** [IITIDIDX597/sp_2019_team3#23]
As a rescuer I want to have the possibility to deny assistance opportunities so that I can better flexibilize my time.

**Comment by ellesia** [comment]
We must have been working on them at the same time. This is very similar to the other.

**Comment by akallish** [comment]
@ellesia @pchaudhary02 @lannesnunes Thanks for using tags to specific sub-hills for your stories but an epic names a body of work like "logging into the system" "Completing a module" etc. They should be descriptive.

However you need to put the sub-hill statement in this story so you can trace the story structure to the intent of the sub-hill. Otherwise it is hard to improve upon.

Here is an iteration of this story to consider: 

**As a** rescuer
**I want** to have the possibility to decline specific assistance opportunities 
**So that** I can better (flexibilize? What does that mean?) my time.
